### ISSUE TITLE
Issues with some dates

### ISSUE THREAD

**Issue by efstathiosntonas** [gunet/openeclass#36]
Hey guys, i think you should take a look in this issue:

https://www.reddit.com/r/greece/comments/h0wj4t/%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9_%CE%B4%CF%85%CE%BD%CE%B1%CF%84%CF%8C%CE%BD_%CE%BD%CE%B1_%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9_%CF%84%CF%8C%CF%83%CE%BF_%CE%AC%CF%87%CF%81%CE%B7%CF%83%CF%84%CE%BF%CE%B9_%CE%BA%CE%B9_%CF%8C%CE%BC%CF%89%CF%82_%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I think there is some data inconsistency somewhere and filters are getting messy.

**Comment by adia** [comment]
Thanks for the notification! There is no issue with the platform itself here, all problems mentioned in the discussion are in the course description, metadata and placement in the appropriate semester, and should be fixed by the professor. In fact, concerning the last issue, they are notified about the problem via this warning in the course home page:
![image](https://user-images.githubusercontent.com/911391/84404936-1fbaa000-ac10-11ea-8a1c-cc31de01e28f.png)
