### ISSUE TITLE
net:: ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by mbouster** [gunet/openeclass#44]
In the mobile application app , when broswing components of the lessons the above error appears.

The webpage is not available 

net:: ERR_CLEARTEXT_NOT_PERMITTED

**Comment by adia** [comment]
Are you connecting to an Open eClass installation which doesn't support https? (ie. the URL is http://... and not https://...)

If so, could you contact the site admins and ask about upgrading the web server to support https and changing the site URL in the site configuration accordingly? This should fix the problem. These days, secure connections (https) are very strongly recommended.

If the site is indeed available over https, the problem might lie elsewhere - in this case, could you please indicate the site you're trying to connect to so that we can investigate? Thanks!
