### ISSUE TITLE
Can't create exercise

### ISSUE THREAD

**Issue by secure-77** [gunet/openeclass#96]
Hi, 

I can't create an exercise, the following error is shown in the docker logs

```
[Sun Jun 16 15:31:27.645809 2024] [php:notice] [pid 7103] [client 192.168.178.69:60285] <p>In file <b>/var/www/html/modules/exercise/exercise.class.php</b> on line <b>788</b> : <i>Unable to execute statement:"Unknown column 'options' in 'field list'", sqlstate:"1054", errornum:"42S22", \tstatement:"INSERT INTO `exercise`                    (course_id, title, description, type, `range`, start_date, end_date,                     temp_save, time_constraint, attempts_allowed,                     random, shuffle, active, results, score, ip_lock, password_lock,                     assign_to_specific, continue_time_limit, calc_grade_method, general_feedback, options)                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", \telapsed:1718541087.0006</i></p>, referer: http://192.168.178.77/modules/exercise/admin.php?course=SEC101&NewExercise=Yes
[Sun Jun 16 15:31:27.646532 2024] [php:warn] [pid 7103] [client 192.168.178.69:60285] PHP Warning:  Attempt to read property "lastInsertID" on null in /var/www/html/modules/exercise/exercise.class.php on line 798, referer: http://192.168.178.77/modules/exercise/admin.php?course=SEC101&NewExercise=Yes
[Sun Jun 16 15:31:27.649321 2024] [php:notice] [pid 7103] [client 192.168.178.69:60285] <p>In file <b>/var/www/html/modules/search/indexer.class.php</b> on line <b>440</b> : <i>Unable to execute statement:"Column 'resource_id' cannot be null", sqlstate:"1048", errornum:"23000", \tstatement:"INSERT INTO idx_queue_async             (user_id, request_type, resource_type, resource_id)             VALUES (?, ?, ?, ?)", \telapsed:1718541087.0004</i></p>, referer: http://192.168.178.77/modules/exercise/admin.php?course=SEC101&NewExercise=Yes
192.168.178.69 - - [16/Jun/2024:15:31:27 +0300] "POST /modules/exercise/admin.php?course=SEC101&NewExercise=Yes HTTP/1.1" 303 498 "http://192.168.178.77/modules/exercise/admin.php?course=SEC101&NewExercise=Yes" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
[Sun Jun 16 15:31:27.661556 2024] [php:notice] [pid 7103] [client 192.168.178.69:60285] <p>In file <b>/var/www/html/modules/exercise/exercise.class.php</b> on line <b>114</b> : <i>Unable to execute statement:"Unknown column 'options' in 'field list'", sqlstate:"1054", errornum:"42S22", \tstatement:"SELECT title, description, general_feedback, type, `range`, start_date, end_date, temp_save, time_constraint,                                                    attempts_allowed, random, shuffle, active, public, results, score, ip_lock, password_lock,                                                    assign_to_specific, calc_grade_method, continue_time_limit, options                                                FROM `exercise` WHERE course_id = ? AND id = ?", \telapsed:1718541087.0003</i></p>, referer: http://192.168.178.77/modules/exercise/admin.php?course=SEC101&NewExercise=Yes
```

It seems the column `options` is missing in the exercise database table. I already run the db upgrade from the gui, but it didn't fixed the problem

**Comment by jexi** [comment]
Hi

Table exercise has not been created. The correct sql statement concerning table exercise is the following:

CREATE TABLE `exercise` (
  `id` int NOT NULL AUTO_INCREMENT,
  `course_id` int NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci,
  `type` tinyint unsigned NOT NULL DEFAULT '1',
  `range` tinyint DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `temp_save` tinyint(1) NOT NULL DEFAULT '0',
  `time_constraint` int DEFAULT '0',
  `attempts_allowed` int DEFAULT '0',
  `random` smallint NOT NULL DEFAULT '0',
  `shuffle` smallint NOT NULL DEFAULT '0',
  `active` tinyint DEFAULT NULL,
  `public` tinyint NOT NULL DEFAULT '1',
  `results` tinyint(1) NOT NULL DEFAULT '1',
  `score` tinyint(1) NOT NULL DEFAULT '1',
  `ip_lock` text CHARACTER SET ascii COLLATE ascii_bin,
  `password_lock` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `assign_to_specific` tinyint NOT NULL DEFAULT '0',
  `continue_time_limit` int NOT NULL DEFAULT '0',
  `calc_grade_method` tinyint DEFAULT '1',
  `general_feedback` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci,
  `options` text COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `exer_index` (`course_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1005 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

You can run the query either from mysql command line or from an administration mysql tool

The above error has been fixed in the forthcoming version 4.0.

Regards
